<?php
namespace Database\Seeders;

use App\Models\Lokasi;
use Illuminate\Database\Seeder;

class LokasiSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'kode'               => 'PUSAT',
                'nama'               => 'KANTOR PUSAT',
                'latitude'           => -6.2088,
                'longitude'          => 106.8456,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Jl. Gatot Subroto No. 123, Jakarta Selatan',
                'telepon'            => '021-12345678',
            ],
            [
                'kode'               => 'INDRAMAYU',
                'nama'               => 'INDRAMAYU - PAK KISNO',
                'latitude'           => -6.2088,
                'longitude'          => 106.8456,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Jl. Gatot Subroto No. 123, Jakarta Selatan',
                'telepon'            => '0234-567890',
            ],
            [
                'kode'               => 'SUBANG',
                'nama'               => 'SUBANG - PAK ANDI',
                'latitude'           => -6.2088,
                'longitude'          => 106.8456,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Jl. Gatot Subroto No. 123, Jakarta Selatan',
                'telepon'            => '0260-789012',
            ],
            [
                'kode'               => 'CIREBON',
                'nama'               => 'CIREBON - PAK IBAH',
                'latitude'           => -6.7320,
                'longitude'          => 108.5523,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Cirebon, Jawa Barat',
                'telepon'            => '0231-456789',
            ],
            [
                'kode'               => 'LAMPUNG1',
                'nama'               => 'LAMPUNG 1 - DAVINA',
                'latitude'           => -5.4501,
                'longitude'          => 105.2678,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Bandar Lampung, Lampung',
                'telepon'            => '0721-888999',
            ],
            [
                'kode'               => 'LAMPUNG2',
                'nama'               => 'LAMPUNG 2 - PAK CARSA',
                'latitude'           => -5.4501,
                'longitude'          => 105.2678,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Bandar Lampung, Lampung',
                'telepon'            => '0721-123456',
            ],
            [
                'kode'               => 'LAMPUNG3',
                'nama'               => 'LAMPUNG 3 - BU FATIMAH',
                'latitude'           => -5.4501,
                'longitude'          => 105.2678,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Bandar Lampung, Lampung',
                'telepon'            => '0721-987654',
            ],
            [
                'kode'               => 'CILACAP',
                'nama'               => 'CILACAP - BU ASMI',
                'latitude'           => -7.7267,
                'longitude'          => 109.0090,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Cilacap, Jawa Tengah',
                'telepon'            => '0282-654321',
            ],
            [
                'kode'               => 'GROBOGAN',
                'nama'               => 'GROBOGAN - PAK ALI',
                'latitude'           => -7.0136,
                'longitude'          => 110.9158,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Grobogan, Jawa Tengah',
                'telepon'            => '0292-345678',
            ],
            [
                'kode'               => 'PONOROGO',
                'nama'               => 'PONOROGO - PAK PRAS',
                'latitude'           => -7.8719,
                'longitude'          => 111.4629,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Ponorogo, Jawa Timur',
                'telepon'            => '0352-777888',
            ],
            [
                'kode'               => 'BANYUWANGI',
                'nama'               => 'BANYUWANGI - PAK NURALIN',
                'latitude'           => -8.2191,
                'longitude'          => 114.3691,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Banyuwangi, Jawa Timur',
                'telepon'            => '0333-999000',
            ],
            [
                'kode'               => 'BLITAR',
                'nama'               => 'BLITAR - PAK MAJID',
                'latitude'           => -8.0983,
                'longitude'          => 112.1681,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Blitar, Jawa Timur',
                'telepon'            => '0342-111222',
            ],
            [
                'kode'               => 'SRAGEN',
                'nama'               => 'SRAGEN - PAK SUGIYANTO',
                'latitude'           => -7.4305,
                'longitude'          => 111.0184,
                'jam_masuk_mulai'    => '07:30:00',
                'jam_masuk_selesai'  => '08:30:00',
                'jam_keluar_mulai'   => '16:30:00',
                'jam_keluar_selesai' => '17:30:00',
                'radius'             => 100,
                'alamat'             => 'Sragen, Jawa Tengah',
                'telepon'            => '0271-333444',
            ],
        ];

        foreach ($locations as $location) {
            Lokasi::create($location);
        }
    }
}
